server:
  port: xxxx
datasource:
  driverName: mysql
  host: xx.xx.xx.xx
  port: 3306
  database: xxx
  username: xxx
  password: xxx
  charset: utf8
  loc: Asia/Shanghai
monitor:
  AppKey: xxxxxxxxxxxxxxxx
  Secret: xxxxxxxxxxxxxxxx
  AccessMonitorTokenUrl: xxxxxxxxxxxxxxxx
  GetStreamAddressUrl: xxxxxxxxxxxx
newcollar:
  login-url: xxxxxxxxxxxx
  get-realtime-url: xxxxxxxxxxxx
  get-history-url: xxxxxxxxxxxxx
  uname: xxxxx
  psw: xxxxxx
mongodb:
  host: xx.xx.xx.xx
  port: 27017
  database: xxxxxx
  collar: xxxxxx
  fio: xxxxxx
  position-collar: xxxxxx
  username: xxxx
  password: xxxxxx
fence:
  spec: 10s
geo:
  coordinates: GCJ-02
biology:
  picturedir: xxxx/assets/biology_pictures/
emqx:
  host: 124.70.208.224
  port: 1883
  username: xumu
  password: xumu@123456
  collar: collar/#
  fio: smartag01/#
  position-collar: poscollar/#