server:
  port: 5930
datasource:
  driverName: mysql
  host: 120.78.73.102
  port: 3306
  database: smartag
  username: root
  password: 12312378945dhyDHY,
  charset: utf8
  loc: Asia/Shanghai
monitor:
  AppKey: a4d8bacae29c4924a68eb65433ac6f1c
  Secret: 4c7f917e151d1b40c9376527dff32354
  AccessMonitorTokenUrl: https://open.ys7.com/api/lapp/token/get
  GetStreamAddressUrl: https://open.ys7.com/api/lapp/v2/live/address/get
newcollar:
  login-url: http://lora.yimaiiot.com:59000/app/login
  get-realtime-url: http://lora.yimaiiot.com:59000/app/realtime/getDeviceData
  get-history-url: http://lora.yimaiiot.com:59000/app/realtime/getTimeData
  uname: scnd
  psw: 123456
mongodb:
  host: 120.78.73.102
  port: 27017
  database: IOT-sensor-data
  collar: electronic-collar
  fio: FIO-sensor
  username: root
  password: 123456
fence:
  spec: 10s
geo:
  coordinates: GCJ-02
biology:
  picturedir: /home/ck/backend/assets/biology_pictures/
