server:
  port: 5930
datasource:
  driverName: mysql
  host: localhost
  port: 3306
  database: farm
  username: root
  password: 123456
  charset: utf8
  loc: Asia/Shanghai
monitor:
  AppKey: xxxxxxxxxxxxxxxx
  Secret: xxxxxxxxxxxxxxxx
  AccessMonitorTokenUrl: xxxxxxxxxxxxxxxx
  GetStreamAddressUrl: xxxxxxxxxxxx
newcollar:
  login-url: xxxxxxxxxxxx
  get-realtime-url: xxxxxxxxxxxx
  get-history-url: xxxxxxxxxxxxx
  uname: xxxxx
  psw: xxxxxx
mongodb:
  host: localhost
  port: 27017
  database: xxxxxx
  collar: xxxxxx
  fio: xxxxxx
  position-collar: xxxxxx
  username: root
  password: 123456
geo:
  coordinates: GCJ-02
biology:
  picturedir: absolute_path_of_project/assets/biology_pictures/
emqx:
  host: localhost
  port: 1883
  username: root
  password: emqx@123456
  collar: collar/#
  fio: fio/#
  position-collar: poscollar/#